const LEAD_STATES = {
  IDLE: "IDLE",
  LEAD_FORM: "LEAD_FORM",
  ADMIN_REPLY_TO_LEAD: "ADMIN_REPLY_TO_LEAD"
};

const LEAD_STEPS = {
  ASK_PHONE: "ASK_PHONE",
  ASK_PHONE_MANUAL: "ASK_PHONE_MANUAL",
  WAIT_ADMIN_MESSAGE: "WAIT_ADMIN_MESSAGE"
};

module.exports = {
  LEAD_STATES,
  LEAD_STEPS
};